services:
  - type: web
    name: acopio
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: acopio-db
          property: connectionString

databases:
  - name: acopio-db
    plan: free
